# Generated by Django 4.0.3 on 2022-03-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpairs',
            old_name='symbols',
            new_name='symbol_pair',
        ),
        migrations.RenameField(
            model_name='userpairs',
            old_name='chat_id',
            new_name='user_bot',
        ),
        migrations.AlterUniqueTogether(
            name='userpairs',
            unique_together={('user_bot', 'symbol_pair')},
        ),
    ]
