# Generated by Django 4.0.3 on 2022-03-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0002_rename_symbols_userpairs_symbol_pair_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbolpairs',
            old_name='time_frame',
            new_name='interval',
        ),
        migrations.AlterUniqueTogether(
            name='symbolpairs',
            unique_together={('symbol1', 'symbol2', 'interval')},
        ),
    ]
