# Generated by Django 4.0.3 on 2022-03-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0003_rename_time_frame_symbolpairs_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolpairs',
            name='need_percent',
            field=models.IntegerField(null=True),
        ),
    ]
