# Generated by Django 4.0.3 on 2022-03-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0004_symbolpairs_need_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolpairs',
            name='need_percent',
        ),
        migrations.AddField(
            model_name='symbolpairs',
            name='close_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='symbolpairs',
            name='open_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userbot',
            name='mode',
            field=models.CharField(choices=[('H', 'HARD'), ('L', 'LITE')], default='L', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userpairs',
            name='status',
            field=models.CharField(choices=[('N', 'NONE'), ('O', 'OPEN'), ('C', 'CLOSE')], default='N', max_length=10),
        ),
    ]
