# Generated by Django 4.0.3 on 2022-03-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0006_userbot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='api_key',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userbot',
            name='api_secret',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
