# Generated by Django 4.0.3 on 2022-03-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0007_userbot_api_key_userbot_api_secret'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpairs',
            unique_together=set(),
        ),
    ]
