# Generated by Django 4.0.3 on 2022-03-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0010_whitelist_alter_userpairs_symbol_pair'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SymbolPairs',
            new_name='SymbolPair',
        ),
        migrations.RenameModel(
            old_name='UserPairs',
            new_name='UserPair',
        ),
        migrations.AlterModelOptions(
            name='symbolpair',
            options={'verbose_name_plural': 'Symbols'},
        ),
        migrations.AlterModelOptions(
            name='userbot',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userpair',
            options={'verbose_name_plural': 'User pairs'},
        ),
        migrations.AlterModelOptions(
            name='whitelist',
            options={'verbose_name_plural': 'White List'},
        ),
    ]
