# Generated by Django 4.0.3 on 2022-03-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0011_rename_symbolpairs_symbolpair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
