# Generated by Django 4.0.3 on 2022-03-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0012_userbot_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='auto_mode',
            field=models.BooleanField(default=False),
        ),
    ]
