# Generated by Django 4.0.3 on 2022-03-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0013_userbot_auto_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='default_deposit',
            field=models.IntegerField(default=100),
        ),
    ]
