# Generated by Django 4.0.3 on 2022-03-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0014_userbot_default_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolpair',
            name='long',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='symbolpair',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='symbolpair',
            name='short',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
