# Generated by Django 4.0.3 on 2022-03-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0016_remove_symbolpair_long_remove_symbolpair_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpair',
            old_name='order_id',
            new_name='order_id_long',
        ),
        migrations.AddField(
            model_name='userpair',
            name='order_id_short',
            field=models.IntegerField(null=True),
        ),
    ]
