# Generated by Django 4.0.3 on 2022-03-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0019_alter_userbot_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolpair',
            name='close_percent',
        ),
        migrations.RemoveField(
            model_name='symbolpair',
            name='open_percent',
        ),
        migrations.RemoveField(
            model_name='userpair',
            name='order_id_long',
        ),
        migrations.RemoveField(
            model_name='userpair',
            name='order_id_short',
        ),
        migrations.AddField(
            model_name='userpair',
            name='close_percent',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='userpair',
            name='open_percent',
            field=models.FloatField(default=3.0),
        ),
        migrations.CreateModel(
            name='UserPairAutoMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'NONE'), ('O', 'OPEN'), ('C', 'CLOSE')], default='N', max_length=10)),
                ('order_id_short', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=15)),
                ('order_id_long', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=15)),
                ('symbol_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='binanceBot.symbolpair')),
                ('user_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanceBot.userbot')),
            ],
            options={
                'verbose_name_plural': 'User pairs auto mode',
                'unique_together': {('user_bot', 'symbol_pair')},
            },
        ),
    ]
