# Generated by Django 4.0.3 on 2022-03-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0020_remove_symbolpair_close_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpairautomode',
            name='user_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanceBot.userbot', unique=True),
        ),
    ]
