# Generated by Django 4.0.3 on 2022-03-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0021_alter_userpairautomode_user_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpairautomode',
            name='user_bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='binanceBot.userbot'),
        ),
    ]
