# Generated by Django 4.0.3 on 2022-03-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0022_alter_userpairautomode_user_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbot',
            old_name='default_deposit',
            new_name='deposit',
        ),
        migrations.AddField(
            model_name='userbot',
            name='close_pnl',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='userbot',
            name='open_percent',
            field=models.FloatField(default=3),
        ),
        migrations.CreateModel(
            name='OpenPairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.FloatField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='binanceBot.symbolpair')),
                ('user_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanceBot.userbot')),
            ],
        ),
    ]
