# Generated by Django 4.0.3 on 2022-03-13 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0024_confirmationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationrequest',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='confirmationrequest',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 15, 15, 44, 690161)),
        ),
    ]
