# Generated by Django 4.0.3 on 2022-03-13 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0026_alter_confirmationrequest_create_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationrequest',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 12, 46, 34, 622463, tzinfo=utc)),
        ),
    ]
