# Generated by Django 4.0.3 on 2022-03-13 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0029_alter_openpairs_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnorePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('ignore_time', models.IntegerField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanceBot.symbolpair')),
                ('user_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanceBot.userbot')),
            ],
        ),
    ]
