# Generated by Django 4.0.3 on 2022-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0030_ignorepair'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpairautomode',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpairautomode',
            name='symbol_pair',
        ),
        migrations.RemoveField(
            model_name='userpairautomode',
            name='user_bot',
        ),
        migrations.AlterModelOptions(
            name='openpairs',
            options={'verbose_name_plural': 'Open pairs'},
        ),
        migrations.AddField(
            model_name='openpairs',
            name='long',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='openpairs',
            name='short',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='openpairs',
            unique_together={('user_bot', 'pair')},
        ),
        migrations.DeleteModel(
            name='UserPair',
        ),
        migrations.DeleteModel(
            name='UserPairAutoMode',
        ),
    ]
