# Generated by Django 4.0.3 on 2022-03-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binanceBot', '0031_alter_userpairautomode_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenPairs',
            new_name='OpenPair',
        ),
        migrations.RenameModel(
            old_name='SymbolPair',
            new_name='Pair',
        ),
        migrations.AlterUniqueTogether(
            name='confirmationrequest',
            unique_together={('user_bot', 'pair')},
        ),
        migrations.AlterUniqueTogether(
            name='ignorepair',
            unique_together={('user_bot', 'pair')},
        ),
    ]
